### ISSUE TITLE
Singularity pulling problem

### ISSUE THREAD

**Issue by rramij** [ratt-ru/Stimela#694]
Hi,
I am trying to install stimela with singularity, but having the problem shown below.
When I am running the following command:
**stimela pull --singularity --pull-folder /home/ramij/stimela**
I am getting the following error.
.
.
2020/12/16 18:20:09  info unpack layer: sha256:104a3ec3587f31497a0f2bf0ec6af214bdff5141f9e7de51cac3568080c18198
2020/12/16 18:20:09  info unpack layer: sha256:1c833a58074d097bb3b59beec106a2290b071f5cda1158105b39f4e0e05b88be
2020/12/16 18:20:11  info unpack layer: sha256:5a424948411eaa63e57cc6f817865b444b32a5f130c57b5bd7bccdc2e3e03b61
INFO:    Creating SIF file...
FATAL:   While making image from oci registry: error copying image out of cache: could not open temporary file for copy: failed to create temporary file: open /singularity_images/tmp-copy-410873205: no such file or directory
Traceback (most recent call last):
  File "/home/ramij/stimela/venv3/bin/stimela", line 11, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/home/ramij/stimela/venv3/lib/python3.6/site-packages/stimela/main.py", line 567, in main
    _cmd(argv)
  File "/home/ramij/stimela/venv3/lib/python3.6/site-packages/stimela/main.py", line 293, in pull
    image, simage, directory=pull_folder, force=args.force)
  File "/home/ramij/stimela/venv3/lib/python3.6/site-packages/stimela/singularity.py", line 46, in pull
    name, fp])
  File "/home/ramij/stimela/venv3/lib/python3.6/site-packages/stimela/utils/xrun_poll.py", line 227, in xrun
    raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
stimela.utils.StimelaCabRuntimeError: cd /home/ramij/stimela && singularity returns error code 255
(venv3) [ramij@astro100 stimela]$

Please help me resolve this problem.

**Comment by o-smirnov** [comment]
That's pretty strange, it's failing in the singularity build with an error I have not seen before:
```
FATAL: While making image from oci registry: error copying image out of cache: could not open temporary file for copy: failed to create temporary file: open /singularity_images/tmp-copy-410873205: no such file or directory
```
Do you have enough disk space, quota, etc.?

**Comment by rramij** [comment]
I am installing it in the home directory, and it has a lot of space. I am putting the disk space output below.

(venv3) [ramij@astro100 stimela]$ pwd
/home/ramij/stimela
(venv3) [ramij@astro100 stimela]$ df -kh .
Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/centos-home   72T   32T   40T  45% /home
(venv3) [ramij@astro100 stimela]$

**Comment by o-smirnov** [comment]
It's a bit strange that it's trying to open ``/singularity_images/tmp-copy-410873205``, rather than something under ``/tmp`` or your home dir. Can you check your environment settings, there's variables like SINGULARITY_TMPDIR and SINGULARITY_CACHEDIR that control this...

**Comment by rramij** [comment]
I think I have messed up during Singularity installation. I wanted it to be installed in the /home dir, but I think it didn't.

Here are the Singularity Makefile source locations

# source/build locations
BUILDDIR := .
BUILDDIR_ABSPATH := /home/ramij/singularity/builddir
SOURCEDIR := /home/ramij/singularity
SCRIPTSDIR := /home/ramij/singularity/mlocal/scripts
CONTRIBDIR := 
PREFIX := /usr/local
EXECPREFIX := /usr/local
BINDIR := /usr/local/bin
SBINDIR := /usr/local/sbin
LIBEXECDIR := /usr/local/libexec
DATAROOTDIR := /usr/local/share
DATADIR := /usr/local/share
SYSCONFDIR := /usr/local/etc
SHAREDSTATEDIR := /usr/local/com
LOCALSTATEDIR := /usr/local/var
RUNSTATEDIR := /usr/local/var/run
INCLUDEDIR := /usr/local/include
OLDINCLUDEDIR := /usr/include
DOCDIR := /usr/local/share/doc/singularity
INFODIR := /usr/local/share/info
HTMLDIR := /usr/local/share/doc/singularity
DVIDIR := /usr/local/share/doc/singularity
PDFDIR := /usr/local/share/doc/singularity
PSDIR := /usr/local/share/doc/singularity
LIBDIR := /usr/local/lib
LOCALEDIR := /usr/local/share/locale
MANDIR := /usr/local/share/man
RPMPREFIX:=

The singularity seems to be installed in /usr/local, and there is not enough space for Stimela installation (only 38 GB available).

I am trying to install Singularity in /home dir, and see if the problem still remains.

**Comment by viralp** [comment]
Hi, I am also getting the following error while pulling images -

>stimela pull -s

# running cd . && singularity pull  --name stimela_pyddi_1.1.3.sif docker://stimela/pyddi:1.1.3
# FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://stimela/pyddi:1.1.3: Error reading manifest 1.1.3 in docker.io/stimela/pyddi: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
Traceback (most recent call last):
  File "/home/vparekh/venv/bin/stimela", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/vparekh/Stimela/bin/stimela", line 11, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/home/vparekh/Stimela/stimela/main.py", line 567, in main
    _cmd(argv)
  File "/home/vparekh/Stimela/stimela/main.py", line 293, in pull
    image, simage, directory=pull_folder, force=args.force)
  File "/home/vparekh/Stimela/stimela/singularity.py", line 46, in pull
    name, fp])
  File "/home/vparekh/Stimela/stimela/utils/xrun_poll.py", line 227, in xrun
    raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
stimela.utils.StimelaCabRuntimeError: cd . && singularity returns error code 255

**Comment by o-smirnov** [comment]
That's the new docker rate limit restrictions. @SpheMakh has [a fix in master](https://github.com/ratt-ru/Stimela/issues/687) but no release yet. Which machine are you on?

**Comment by viralp** [comment]
Stevie

**Comment by o-smirnov** [comment]
Ouch, that's unexpected. Stevie has a docker mirror configured, but obviously this didn't solve the problem...

At the moment it seems we can pull again, the docker timeout has expired.

**Comment by gigjozsa** [comment]
Yes, I'm having the same problem with Singularity. Could it be that the registry has been changed for docker only?

**Comment by o-smirnov** [comment]
Yeah good call @gigjozsa. Indeed singularity doesn't even look at the docker config (and, come to think of it, why would it -- docker doesn't need to be installed for singularity to work!) and goes directly to the docker hub.

There's a solution, but it needs to be fixed in Stimela. https://github.com/ratt-ru/Stimela/blob/master/stimela/singularity.py#L34 Instead of pulling ``docker://stimela/wsclean``, it should pull ``docker://docker-registry.mirror.ac.za/stimela/wsclean``.

Please make the fix in your local version and tell us if it works?

**Comment by SpheMakh** [comment]
Fixed in branch `issue-687`

**Comment by viralp** [comment]
@Sphe thanks but with this new branch getting the following error 
```
# running cd . && singularity pull  --name stimela_sofia_1.2.5-1.sif docker://quay.io/stimela/sofia:1.2.5-1
# INFO:    Using cached SIF image
# FATAL:   While making image from oci registry: error copying image out of cache: could not open temporary file for copy: failed to create temporary file: open /data3/vparekh/singularity/tmp-copy-174265682: no such file or directory
Traceback (most recent call last):
  File "/home/vparekh/venv/bin/stimela", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/vparekh/Stimela/bin/stimela", line 11, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/home/vparekh/Stimela/stimela/main.py", line 388, in main
    _cmd(argv)
  File "/home/vparekh/Stimela/stimela/main.py", line 296, in pull
    image, simage, directory=pull_folder, force=args.force)
  File "/home/vparekh/Stimela/stimela/singularity.py", line 46, in pull
    name, fp])
  File "/home/vparekh/Stimela/stimela/utils/xrun_poll.py", line 227, in xrun
    raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
stimela.utils.StimelaCabRuntimeError: cd . && singularity returns error code 255
```
@Oleg I also tried to modify the local version but still error persist
```
# running cd . && singularity pull  --name stimela_sharpener_1.2.0.sif docker://docker-registry.mirror.ac.za/stimela/
# FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://docker-registry.mirror.ac.za/stimela/: unable to parse image name docker://docker-registry.mirror.ac.za/stimela/: invalid reference format
Traceback (most recent call last):
  File "/home/vparekh/venv/bin/stimela", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/vparekh/Stimela/bin/stimela", line 11, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/home/vparekh/Stimela/stimela/main.py", line 388, in main
    _cmd(argv)
  File "/home/vparekh/Stimela/stimela/main.py", line 296, in pull
    image, simage, directory=pull_folder, force=args.force)
  File "/home/vparekh/Stimela/stimela/singularity.py", line 47, in pull
    name, fp])
  File "/home/vparekh/Stimela/stimela/utils/xrun_poll.py", line 227, in xrun
    raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
stimela.utils.StimelaCabRuntimeError: cd . && singularity returns error code 255
```

**Comment by gigjozsa** [comment]
For me #688 seems to work (so far).

**Comment by o-smirnov** [comment]
I think your modification is incorrect. I can see it's trying to pull ``docker://docker-registry.mirror.ac.za/stimela/``, but the image name  itself ("sharpener" or whatever) is missing....
